"""Execute the exact pre-change source of the frozen long-forecast modules.

`us-sec-long-v1` and `us-sec-long-v2` are frozen contracts: their config
bytes, effective hash, eligibility, reason wording, and both successful and
withheld payloads must be identical before and after the `us-sec-long-v3`
evidence-selection work. Asserting that against hand-written expectations
only proves the expectations, so this helper runs the *actual* base revision's
code against the same deterministic fixture and diffs complete payloads.

Provenance
----------
`BASE_SHA` is the revision the `us-sec-long-v3` slice branched from. The base
sources are read straight out of the object database with ``git show`` and
imported into a throwaway module namespace; nothing on disk is modified and
no base file is copied into the working tree.

Availability
------------
A shallow or object-pruned checkout may not contain `BASE_SHA`. In that case
`base_sources_available()` is ``False`` and the live differential test is
skipped -- but the committed golden payloads in
``tests/data/long_frozen_base_payloads.json`` were generated by this exact
harness and are still compared on every run, so the frozen contract is never
left unproven.

Regeneration
------------
Regenerating that golden requires the base objects. `base_source_checksums()`
records the exact bytes each golden was generated from, and
`BaseRevisionUnavailableError` is raised rather than falling back to anything
the working tree can produce. A golden labelled with `BASE_SHA` must always
have been produced by `BASE_SHA`'s own code.
"""

from __future__ import annotations

import hashlib
import importlib.util
import subprocess
import sys
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType

BASE_SHA = "38df10f014caf5ed81a57ac020b31f0dd634fd37"


class BaseRevisionUnavailableError(RuntimeError):
    """The exact base objects are not readable from the local object database.

    Anything derived from the base revision -- above all a committed golden
    labelled with `BASE_SHA` -- must come from `BASE_SHA`'s own bytes. When
    those bytes cannot be read there is no safe fallback, so the operation
    refuses instead of substituting the working tree.
    """


#: Import order matters: each module is injected under its real dotted name so
#: the next one resolves its ``from stanstock...`` imports against the base
#: version rather than the working-tree version.
BASE_MODULE_PATHS: tuple[tuple[str, str], ...] = (
    ("stanstock.data.sec_fundamentals", "src/stanstock/data/sec_fundamentals.py"),
    (
        "stanstock.research.long_forecast_config",
        "src/stanstock/research/long_forecast_config.py",
    ),
    ("stanstock.research.long_forecasts", "src/stanstock/research/long_forecasts.py"),
)

REPO_ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True, slots=True)
class BaseModules:
    base_sha: str
    source_sha256: dict[str, str]
    long_forecasts: ModuleType
    long_forecast_config: ModuleType
    sec_fundamentals: ModuleType


def base_sources_available() -> bool:
    try:
        base_source_checksums()
    except BaseRevisionUnavailableError:
        return False
    return True


def base_source_checksums() -> dict[str, str]:
    """SHA-256 of each base module's exact bytes, keyed by repository path.

    Raises `BaseRevisionUnavailableError` when the base objects are not
    present, so no caller can silently proceed against working-tree code.
    """
    return {
        path: hashlib.sha256(_read_base_source(path)).hexdigest()
        for _name, path in BASE_MODULE_PATHS
    }


def _read_base_source(path: str) -> bytes:
    try:
        return subprocess.run(
            ["git", "show", f"{BASE_SHA}:{path}"],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError) as error:
        raise BaseRevisionUnavailableError(
            f"Base revision object {BASE_SHA}:{path} is not readable from the local "
            "git object database"
        ) from error


@contextmanager
def base_long_forecast_modules() -> Iterator[BaseModules]:
    """Temporarily import the base revision's frozen forecast modules.

    The working-tree modules are restored on exit, including on failure.
    Modules that already imported these names by value keep their own
    references, so nothing outside this block observes the swap.
    """
    original: dict[str, ModuleType | None] = {
        name: sys.modules.get(name) for name, _path in BASE_MODULE_PATHS
    }
    loaded: dict[str, ModuleType] = {}
    checksums: dict[str, str] = {}
    try:
        for name, path in BASE_MODULE_PATHS:
            source = _read_base_source(path)
            checksums[path] = hashlib.sha256(source).hexdigest()
            module = _module_from_source(name=name, path=path, source=source)
            sys.modules[name] = module
            loaded[name] = module
        yield BaseModules(
            base_sha=BASE_SHA,
            source_sha256=checksums,
            long_forecasts=loaded["stanstock.research.long_forecasts"],
            long_forecast_config=loaded["stanstock.research.long_forecast_config"],
            sec_fundamentals=loaded["stanstock.data.sec_fundamentals"],
        )
    finally:
        for name, module in original.items():
            if module is None:
                sys.modules.pop(name, None)
            else:
                sys.modules[name] = module


def _module_from_source(*, name: str, path: str, source: bytes) -> ModuleType:
    spec = importlib.util.spec_from_loader(name, loader=None, origin=f"{BASE_SHA}:{path}")
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    module.__file__ = str(REPO_ROOT / path)
    exec(compile(source, f"<{BASE_SHA}:{path}>", "exec"), module.__dict__)
    return module
