# Generated by Django 5.2.17 on 2026-09-05 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('mode', models.CharField(choices=[('backtest', 'Backtest'), ('portfolio', 'Portfolio simulation')], max_length=12)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='running', max_length=12)),
                ('code_revision', models.CharField(max_length=64)),
                ('input_hash', models.CharField(max_length=64)),
                ('result_asset_key', models.CharField(blank=True, max_length=500)),
                ('metrics', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='simulation.simulationdefinition')),
                ('universe_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.universesnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('gross_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('costs', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.listing')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='simulation.simulationrun')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('market_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('weight', models.DecimalField(decimal_places=8, max_digits=12)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.listing')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='simulation.simulationrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'listing', 'observation_date'), name='unique_simulation_holding')],
            },
        ),
    ]
