# Generated by Django 5.2.17 on 2026-09-06 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0004_latest_market_data_session_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('base_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], max_length=3)),
                ('cash_balance', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('average_cost', models.DecimalField(decimal_places=6, max_digits=20)),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.listing')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['listing__ticker'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('oldest_price_date', models.DateField(blank=True, null=True)),
                ('newest_price_date', models.DateField(blank=True, null=True)),
                ('base_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], max_length=3)),
                ('cash_balance', models.DecimalField(decimal_places=6, max_digits=24)),
                ('securities_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('total_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('cost_basis', models.DecimalField(decimal_places=6, max_digits=24)),
                ('unrealized_gain', models.DecimalField(decimal_places=6, max_digits=24)),
                ('return_pct', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('input_hash', models.CharField(max_length=64)),
                ('code_revision', models.CharField(max_length=64)),
                ('return_definition', models.CharField(default='split_adjusted_price_return', max_length=48)),
                ('dividends_included', models.BooleanField(default=False)),
                ('corporate_action_warnings', models.PositiveIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-as_of_date', '-recorded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshotHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_session_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('average_cost', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('cost_basis', models.DecimalField(decimal_places=6, max_digits=24)),
                ('market_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('unrealized_gain', models.DecimalField(decimal_places=6, max_digits=24)),
                ('corporate_action_suspected', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.listing')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfoliosnapshot')),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.dataasset')),
            ],
            options={
                'ordering': ['listing__ticker'],
            },
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_portfolio_name'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('cash_balance__gte', 0)), name='portfolio_cash_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='portfolioholding',
            constraint=models.UniqueConstraint(fields=('portfolio', 'listing'), name='unique_portfolio_holding'),
        ),
        migrations.AddConstraint(
            model_name='portfolioholding',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='portfolio_holding_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='portfolioholding',
            constraint=models.CheckConstraint(condition=models.Q(('average_cost__gt', 0)), name='portfolio_holding_average_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.UniqueConstraint(fields=('portfolio', 'as_of_date', 'input_hash'), name='unique_portfolio_snapshot_input'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('cash_balance__gte', 0)), name='portfolio_snapshot_cash_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('securities_value__gte', 0)), name='portfolio_snapshot_securities_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('total_value__gte', 0)), name='portfolio_snapshot_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('cost_basis__gte', 0)), name='portfolio_snapshot_cost_basis_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshotholding',
            constraint=models.UniqueConstraint(fields=('snapshot', 'listing'), name='unique_portfolio_snapshot_holding'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshotholding',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='portfolio_snapshot_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshotholding',
            constraint=models.CheckConstraint(condition=models.Q(('average_cost__gt', 0)), name='portfolio_snapshot_average_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshotholding',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='portfolio_snapshot_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshotholding',
            constraint=models.CheckConstraint(condition=models.Q(('cost_basis__gt', 0)), name='portfolio_snapshot_holding_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshotholding',
            constraint=models.CheckConstraint(condition=models.Q(('market_value__gt', 0)), name='portfolio_snapshot_holding_value_positive'),
        ),
    ]
