# Generated by Django 5.2.17 on 2026-09-07 01:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

PROTECTED_MODELS = {
    "PortfolioDeposit": "portfolio_portfoliodeposit",
    "PortfolioPerformanceBaseline": "portfolio_portfolioperformancebaseline",
    "PortfolioPlanExecution": "portfolio_portfolioplanexecution",
    "PortfolioPurchase": "portfolio_portfoliopurchase",
}
POSTGRES_FUNCTION = "stanstock_prevent_portfolio_ledger_mutation"


def protect_portfolio_ledger(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "sqlite":
        for model_name, table_name in PROTECTED_MODELS.items():
            table = schema_editor.quote_name(table_name)
            slug = model_name.lower()
            schema_editor.execute(
                f"""
                CREATE TRIGGER portfolio_{slug}_prevent_update
                BEFORE UPDATE ON {table}
                BEGIN
                    SELECT RAISE(ABORT, '{model_name} records are immutable');
                END
                """
            )
            schema_editor.execute(
                f"""
                CREATE TRIGGER portfolio_{slug}_prevent_delete
                BEFORE DELETE ON {table}
                BEGIN
                    SELECT RAISE(ABORT, '{model_name} records are immutable');
                END
                """
            )
        return
    if vendor == "postgresql":
        schema_editor.execute(
            f"""
            CREATE OR REPLACE FUNCTION {POSTGRES_FUNCTION}()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION '%% records are immutable', TG_TABLE_NAME
                    USING ERRCODE = '55000';
            END;
            $$ LANGUAGE plpgsql
            """
        )
        for model_name, table_name in PROTECTED_MODELS.items():
            table = schema_editor.quote_name(table_name)
            trigger = f"portfolio_{model_name.lower()}_prevent_mutation"
            schema_editor.execute(
                f"""
                CREATE TRIGGER {trigger}
                BEFORE UPDATE OR DELETE ON {table}
                FOR EACH ROW EXECUTE FUNCTION {POSTGRES_FUNCTION}()
                """
            )
        return
    raise RuntimeError(f"Unsupported database vendor for portfolio ledger: {vendor}")


def unprotect_portfolio_ledger(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "sqlite":
        for model_name in PROTECTED_MODELS:
            slug = model_name.lower()
            schema_editor.execute(f"DROP TRIGGER IF EXISTS portfolio_{slug}_prevent_update")
            schema_editor.execute(f"DROP TRIGGER IF EXISTS portfolio_{slug}_prevent_delete")
        return
    if vendor == "postgresql":
        for model_name, table_name in PROTECTED_MODELS.items():
            table = schema_editor.quote_name(table_name)
            trigger = f"portfolio_{model_name.lower()}_prevent_mutation"
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger} ON {table}")
        schema_editor.execute(f"DROP FUNCTION IF EXISTS {POSTGRES_FUNCTION}()")


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0005_add_etf_security_type"),
        ("portfolio", "0003_portfolio_construction_metadata_and_more"),
        ("research", "0007_analysis_run_issued_on_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioDeposit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=6, max_digits=24)),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("EUR", "EUR"), ("GBP", "GBP")], max_length=3
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("idempotency_key", models.UUIDField()),
                ("boundary_issue", models.CharField(blank=True, max_length=240)),
                ("cash_balance_after", models.DecimalField(decimal_places=6, max_digits=24)),
                ("note", models.CharField(blank=True, max_length=240)),
            ],
            options={
                "ordering": ["occurred_at", "recorded_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioPlanExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("plan_hash", models.CharField(max_length=64)),
                ("policy_version", models.CharField(max_length=80)),
                ("executed_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("starting_nav", models.DecimalField(decimal_places=6, max_digits=24)),
                ("starting_cash", models.DecimalField(decimal_places=6, max_digits=24)),
                ("ending_cash", models.DecimalField(decimal_places=6, max_digits=24)),
                ("fractional_shares", models.BooleanField()),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-executed_at", "-recorded_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_session_date", models.DateField()),
                (
                    "role",
                    models.CharField(
                        choices=[("core", "Core ETF"), ("satellite", "Stock satellite")],
                        max_length=16,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=24)),
                ("price", models.DecimalField(decimal_places=6, max_digits=20)),
                ("amount", models.DecimalField(decimal_places=6, max_digits=24)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["role", "listing__ticker"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioPerformanceBaseline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("manual_holding_change", "Manual holding change"),
                        ],
                        max_length=40,
                    ),
                ),
                ("boundary_issue", models.CharField(blank=True, max_length=240)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performance_baselines",
                        to="portfolio.portfolio",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performance_baselines",
                        to="portfolio.portfoliosnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="portfolioperformancebaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("boundary_issue", ""), ("snapshot__isnull", False)),
                    models.Q(
                        ("snapshot__isnull", True),
                        models.Q(("boundary_issue", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="portfolio_performance_baseline_state",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="allow_fractional_shares",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="monthly_contribution",
            field=models.DecimalField(decimal_places=6, default=600, max_digits=24),
        ),
        migrations.AddConstraint(
            model_name="portfolio",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_contribution__gt", 0)),
                name="portfolio_monthly_contribution_positive",
            ),
        ),
        migrations.AddField(
            model_name="portfoliodeposit",
            name="boundary_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposit_boundaries",
                to="portfolio.portfoliosnapshot",
            ),
        ),
        migrations.AddField(
            model_name="portfoliodeposit",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposits",
                to="portfolio.portfolio",
            ),
        ),
        migrations.AddField(
            model_name="portfolioplanexecution",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plan_executions",
                to="portfolio.portfolio",
            ),
        ),
        migrations.AddField(
            model_name="portfoliopurchase",
            name="execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="portfolio.portfolioplanexecution",
            ),
        ),
        migrations.AddField(
            model_name="portfoliopurchase",
            name="listing",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="data.listing"),
        ),
        migrations.AddField(
            model_name="portfoliopurchase",
            name="source_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="data.dataasset"
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliodeposit",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "idempotency_key"), name="unique_portfolio_deposit_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliodeposit",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="portfolio_deposit_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliodeposit",
            constraint=models.CheckConstraint(
                condition=models.Q(("cash_balance_after__gte", 0)),
                name="portfolio_deposit_balance_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliodeposit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("boundary_issue", ""), ("boundary_snapshot__isnull", False)),
                    models.Q(
                        ("boundary_snapshot__isnull", True),
                        models.Q(("boundary_issue", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="portfolio_deposit_boundary_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="portfolioplanexecution",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "idempotency_key"),
                name="unique_portfolio_plan_execution_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="portfolioplanexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(("starting_nav__gte", 0)),
                name="portfolio_execution_nav_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="portfolioplanexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(("starting_cash__gte", 0)),
                name="portfolio_execution_start_cash_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="portfolioplanexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(("ending_cash__gte", 0)),
                name="portfolio_execution_end_cash_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliopurchase",
            constraint=models.UniqueConstraint(
                fields=("execution", "listing"), name="unique_execution_purchase_listing"
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliopurchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="portfolio_purchase_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliopurchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)), name="portfolio_purchase_price_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliopurchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="portfolio_purchase_amount_positive"
            ),
        ),
        migrations.RunPython(
            protect_portfolio_ledger,
            unprotect_portfolio_ledger,
        ),
    ]
