# Generated by Django 5.2.17 on 2026-09-05 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('country', models.CharField(max_length=2)),
                ('sector', models.CharField(blank=True, max_length=120)),
                ('industry', models.CharField(blank=True, max_length=160)),
                ('lei', models.CharField(blank=True, db_index=True, max_length=20)),
                ('cik', models.CharField(blank=True, db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderRecord',
            fields=[
                ('provider', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('terms_url', models.URLField(blank=True)),
                ('terms_checked_at', models.DateTimeField(blank=True, null=True)),
                ('usage_scope', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='not_configured', max_length=32)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('config_version', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DataAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('kind', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=120)),
                ('relative_path', models.CharField(max_length=500, unique=True)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('retrieved_at', models.DateTimeField()),
                ('available_at', models.DateTimeField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('schema_version', models.CharField(default='1', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-available_at', '-retrieved_at'],
                'indexes': [models.Index(fields=['provider', 'kind', 'subject', 'available_at'], name='asset_asof_lookup')],
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('security_type', models.CharField(choices=[('common_stock', 'Common stock'), ('adr', 'Depositary receipt')], default='common_stock', max_length=24)),
                ('isin', models.CharField(blank=True, db_index=True, max_length=12)),
                ('name', models.CharField(blank=True, max_length=240)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='data.company')),
            ],
            options={
                'verbose_name_plural': 'securities',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=32)),
                ('exchange_mic', models.CharField(max_length=4)),
                ('provider_symbol', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(max_length=3)),
                ('region', models.CharField(choices=[('us', 'United States'), ('europe', 'Europe')], max_length=12)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='data.security')),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='UniverseSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(choices=[('research', 'Research-grade reconstruction'), ('observed', 'Observed at run time')], max_length=12)),
                ('config_hash', models.CharField(max_length=64)),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='data.universe')),
            ],
            options={
                'ordering': ['-as_of_date', '-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='UniverseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible', models.BooleanField(default=True)),
                ('exclusion_reason', models.CharField(blank=True, max_length=160)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.listing')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='data.universesnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='FundamentalFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('concept', models.CharField(max_length=100)),
                ('source_concept', models.CharField(max_length=240)),
                ('value', models.DecimalField(decimal_places=8, max_digits=32)),
                ('unit', models.CharField(max_length=24)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField()),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('fiscal_period', models.CharField(blank=True, max_length=8)),
                ('accession', models.CharField(max_length=80)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('available_at', models.DateTimeField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('is_amendment', models.BooleanField(default=False)),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='data.company')),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.dataasset')),
            ],
            options={
                'ordering': ['company', 'concept', '-available_at'],
                'indexes': [models.Index(fields=['company', 'concept', 'available_at'], name='fact_asof_lookup')],
                'constraints': [models.UniqueConstraint(fields=('company', 'provider', 'source_concept', 'period_end', 'accession', 'unit'), name='unique_fundamental_vintage')],
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('observation_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('published_at', models.DateTimeField()),
                ('available_at', models.DateTimeField()),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.dataasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'observation_date', 'available_at'), name='unique_fx_vintage')],
            },
        ),
        migrations.CreateModel(
            name='LatestMarketData',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='latest_market_data', serialize=False, to='data.listing')),
                ('observed_at', models.DateTimeField()),
                ('close', models.DecimalField(decimal_places=6, max_digits=20)),
                ('previous_close', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.dataasset')),
            ],
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('ticker', 'exchange_mic', 'valid_from'), name='unique_dated_listing'),
        ),
        migrations.AddConstraint(
            model_name='universesnapshot',
            constraint=models.UniqueConstraint(fields=('universe', 'as_of_date', 'grade'), name='unique_universe_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='universemembership',
            constraint=models.UniqueConstraint(fields=('snapshot', 'listing'), name='unique_universe_membership'),
        ),
    ]
