# Generated by Django 5.2.17 on 2026-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dataasset',
            constraint=models.CheckConstraint(condition=models.Q(('available_at__lte', models.F('retrieved_at'))), name='asset_available_before_retrieval'),
        ),
        migrations.AddConstraint(
            model_name='fundamentalfact',
            constraint=models.CheckConstraint(condition=models.Q(('filed_at__isnull', True), ('available_at__gte', models.F('filed_at')), _connector='OR'), name='fact_available_after_filing'),
        ),
        migrations.AddConstraint(
            model_name='fxrate',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='fx_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='fxrate',
            constraint=models.CheckConstraint(condition=models.Q(('available_at__gte', models.F('published_at'))), name='fx_available_after_publication'),
        ),
        migrations.AddConstraint(
            model_name='latestmarketdata',
            constraint=models.CheckConstraint(condition=models.Q(('close__gt', 0)), name='latest_market_close_positive'),
        ),
        migrations.AddConstraint(
            model_name='latestmarketdata',
            constraint=models.CheckConstraint(condition=models.Q(('previous_close__isnull', True), ('previous_close__gt', 0), _connector='OR'), name='latest_market_previous_close_positive'),
        ),
        migrations.AddConstraint(
            model_name='latestmarketdata',
            constraint=models.CheckConstraint(condition=models.Q(('volume__isnull', True), ('volume__gte', 0), _connector='OR'), name='latest_market_volume_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='listing_valid_date_range'),
        ),
    ]
