# Generated by Django 5.2.17 on 2026-09-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_latest_market_data_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='security_type',
            field=models.CharField(choices=[('common_stock', 'Common stock'), ('adr', 'Depositary receipt'), ('etf', 'Exchange-traded fund')], default='common_stock', max_length=24),
        ),
    ]
