# Generated by Django 5.2.17 on 2026-09-07 17:50

import uuid

import django.db.models.deletion
from django.db import migrations, models

MODEL_NAME = "FundamentalFactEvidence"
TABLE_NAME = "data_fundamentalfactevidence"
POSTGRES_FUNCTION = "stanstock_prevent_evidence_mutation"


def protect_fact_evidence(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    table = schema_editor.quote_name(TABLE_NAME)
    if vendor == "sqlite":
        schema_editor.execute(
            f"""
            CREATE TRIGGER data_fundamentalfactevidence_prevent_update
            BEFORE UPDATE ON {table}
            BEGIN
                SELECT RAISE(ABORT, '{MODEL_NAME} records are immutable');
            END
            """
        )
        schema_editor.execute(
            f"""
            CREATE TRIGGER data_fundamentalfactevidence_prevent_delete
            BEFORE DELETE ON {table}
            BEGIN
                SELECT RAISE(ABORT, '{MODEL_NAME} records are immutable');
            END
            """
        )
        return
    if vendor == "postgresql":
        schema_editor.execute(
            f"""
            CREATE OR REPLACE FUNCTION {POSTGRES_FUNCTION}()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION '%% records are immutable', TG_TABLE_NAME
                    USING ERRCODE = '55000';
            END;
            $$ LANGUAGE plpgsql
            """
        )
        schema_editor.execute(
            f"""
            CREATE TRIGGER data_fundamentalfactevidence_prevent_mutation
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION {POSTGRES_FUNCTION}()
            """
        )
        return
    raise RuntimeError(f"Unsupported database vendor for evidence immutability: {vendor}")


def unprotect_fact_evidence(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    table = schema_editor.quote_name(TABLE_NAME)
    if vendor == "sqlite":
        schema_editor.execute("DROP TRIGGER IF EXISTS data_fundamentalfactevidence_prevent_update")
        schema_editor.execute("DROP TRIGGER IF EXISTS data_fundamentalfactevidence_prevent_delete")
        return
    if vendor == "postgresql":
        schema_editor.execute(
            f"DROP TRIGGER IF EXISTS data_fundamentalfactevidence_prevent_mutation ON {table}"
        )
        return
    raise RuntimeError(f"Unsupported database vendor for evidence immutability: {vendor}")


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0006_sec_fact_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundamentalFactEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("filing", "Filing availability")],
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_links",
                        to="data.fundamentalfact",
                    ),
                ),
                (
                    "source_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.dataasset",
                    ),
                ),
            ],
            options={
                "ordering": ["fact", "role", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fact", "role"),
                        name="unique_fundamental_fact_evidence_role",
                    )
                ],
            },
        ),
        migrations.RunPython(protect_fact_evidence, unprotect_fact_evidence),
    ]
