# Generated by Django 5.2.17 on 2026-09-05 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField()),
                ('target_date', models.DateField()),
                ('horizon', models.CharField(choices=[('short', '1-10 trading days'), ('medium', '6-12 months'), ('long', '3+ years')], max_length=8)),
                ('price_at_prediction', models.DecimalField(decimal_places=6, max_digits=20)),
                ('bear_return', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('base_return', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('bull_return', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('probability_positive', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=6)),
                ('confidence_status', models.CharField(max_length=32)),
                ('insufficiency_reason', models.CharField(blank=True, max_length=240)),
                ('recommendation', models.CharField(choices=[('buy', 'BUY'), ('hold', 'HOLD'), ('avoid', 'AVOID')], max_length=8)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('component_scores', models.JSONField(default=dict)),
                ('model_version', models.CharField(max_length=40)),
                ('config_hash', models.CharField(max_length=64)),
                ('data_cutoff', models.DateTimeField()),
                ('source_assets', models.JSONField(default=list)),
                ('code_revision', models.CharField(max_length=64)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.listing')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField()),
                ('target_date', models.DateField()),
                ('config_version', models.CharField(max_length=40)),
                ('config_hash', models.CharField(max_length=64)),
                ('code_revision', models.CharField(max_length=64)),
                ('status', models.CharField(default='complete', max_length=20)),
                ('universe_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.universesnapshot')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionOutcome',
            fields=[
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='outcome', serialize=False, to='research.prediction')),
                ('evaluated_at', models.DateTimeField()),
                ('evaluation_date', models.DateField()),
                ('status', models.CharField(choices=[('matured', 'Matured'), ('unresolved', 'Unresolved'), ('corporate_event', 'Corporate event')], max_length=20)),
                ('actual_return', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('benchmark_return', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('success', models.BooleanField(null=True)),
                ('resolution', models.CharField(max_length=120)),
                ('error', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('daily_change', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recommendation', models.CharField(choices=[('buy', 'BUY'), ('hold', 'HOLD'), ('avoid', 'AVOID')], max_length=8)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('risk_class', models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH'), ('very_high', 'VERY HIGH')], max_length=12)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=6)),
                ('confidence_status', models.CharField(default='heuristic', max_length=32)),
                ('component_scores', models.JSONField(default=dict)),
                ('short_scenario', models.JSONField(default=dict)),
                ('medium_scenario', models.JSONField(default=dict)),
                ('long_scenario', models.JSONField(default=dict)),
                ('reasons', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('data_quality', models.JSONField(default=dict)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.listing')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='research.analysisrun')),
            ],
            options={
                'ordering': ['-overall_score'],
            },
        ),
        migrations.AddField(
            model_name='prediction',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='research.stockanalysis'),
        ),
        migrations.AddConstraint(
            model_name='stockanalysis',
            constraint=models.UniqueConstraint(fields=('run', 'listing'), name='unique_analysis_listing'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.UniqueConstraint(fields=('listing', 'target_date', 'horizon', 'model_version'), name='unique_prediction_version'),
        ),
    ]
