# Generated by Django 5.2.17 on 2026-09-05 22:32

from importlib import import_module

from django.db import migrations, models

prediction_immutability = import_module(
    "stanstock.research.migrations.0005_reinstate_prediction_immutability"
)


def mark_existing_on_time_runs(apps, schema_editor):
    AnalysisRun = apps.get_model("research", "AnalysisRun")
    runs = AnalysisRun.objects.filter(
        universe_snapshot__grade="observed",
    ).only("pk", "generated_at", "target_date")
    for run in runs.iterator():
        if run.generated_at.date() == run.target_date:
            AnalysisRun.objects.filter(pk=run.pk).update(issued_on_time=True)


def clear_existing_on_time_runs(apps, schema_editor):
    AnalysisRun = apps.get_model("research", "AnalysisRun")
    AnalysisRun.objects.update(issued_on_time=False)


def mark_existing_on_time_predictions(apps, schema_editor):
    Prediction = apps.get_model("research", "Prediction")
    predictions = Prediction.objects.filter(
        analysis__run__issued_on_time=True,
    ).select_related("analysis__run")
    for prediction in predictions.iterator():
        if prediction.generated_at == prediction.analysis.run.generated_at:
            Prediction.objects.filter(pk=prediction.pk).update(issued_on_time=True)


def clear_existing_on_time_predictions(apps, schema_editor):
    Prediction = apps.get_model("research", "Prediction")
    Prediction.objects.update(issued_on_time=False)


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0006_analysis_cutoff_and_risk_insufficiency"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="issued_on_time",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_existing_on_time_runs,
            clear_existing_on_time_runs,
        ),
        migrations.RunPython(
            prediction_immutability.unprotect_predictions,
            prediction_immutability.protect_predictions,
        ),
        migrations.AddField(
            model_name="prediction",
            name="issued_on_time",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_existing_on_time_predictions,
            clear_existing_on_time_predictions,
        ),
        migrations.RunPython(
            prediction_immutability.protect_predictions,
            prediction_immutability.unprotect_predictions,
        ),
    ]
