# Generated by Django 5.2.17 on 2026-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('job_name', 'region', 'target_date'), name='unique_successful_job_target'),
        ),
        migrations.AddConstraint(
            model_name='jobrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'running')), models.Q(models.Q(('status', 'running'), _negated=True), ('finished_at__isnull', False)), _connector='OR'), name='job_finished_at_matches_status'),
        ),
    ]
